about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/urls.py
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.urls import include, path

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

urlpatterns = [
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("adminhost/admin", admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path("", include("posts.urls")),
]

templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">
        <a href="{% url 'about:author' %}">Об авторе</a> | <a href="{% url 'about:tech' %}">Технологии</a>
    </p>
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube © {% now "Y" %}.</p>
</footer> 

templates/includes/menu.html
{% if user.is_authenticated %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}">
                  Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'follow_index' %}">
                Избранные авторы
            </a>
        </li>
    </ul>
{% endif %} 

templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'index' %}"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
            Пользователь: <a href="{% url 'profile' user.username %}">{{ user.username }}</a>.
            {% if user.is_staff %}
                <a class="p-2 text-dark" href="{% url 'admin:index'  %}">Админ-панель</a>
            {% endif %}
            <a class="p-2 text-dark" href="{% url 'new_post' %}">Новый пост</a>
            <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
            <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
            <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
            <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav> 

templates/includes/paginator.html
{% if page.has_other_pages %}
    <nav>
        <ul class="pagination">
            {% if page.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&laquo; Предыдущая</span>
                </li>
            {% endif %}
            {% for i in page.paginator.page_range %}
                {% if page.number == i %}
                    <li class="page-item active">
                        <span class="page-link">{{ i }}
                            <span class="sr-only">(текущая)</span>
                        </span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Следующая &raquo;</span>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %} 